
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: development_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  adapter: mysql2
  database: <%= ENV.fetch("DB_NAME") %>
  username: <%= ENV.fetch("DB_USER") %>
  host: <%= ENV.fetch("DB_HOST") %>
  password: <%= ENV.fetch("DB_PASS") %>
  ssl_mode: verify_identity
  sslca: <%= ENV.fetch("MYSQL_ATTR_SSL_CA") %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>