
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") %>
  host: <%= ENV.fetch("DB_HOST") %>
  password: <%= ENV.fetch("DB_PASS") %>
  ssl_mode: verify_identity
  sslca: <%= ENV.fetch("sslca") %>

development:
  <<: *default
  database: development_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  adapter: mysql2
  database: <%= ENV.fetch("DB_NAME") %>
  username: <%= ENV.fetch("DB_USER") %>
  host: <%= ENV.fetch("DB_HOST") %>
  password: <%= ENV.fetch("DB_PASS") %>
  ssl_mode: verify_identity
  sslca: <%= ENV.fetch("sslca") %>