
default: &default
  adapter: mysql2
  # encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: development_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  # url: <%= (ENV.fetch("JAWSDB_URL") { "mysql://test:test@test.com:3306/test" }).gsub(/mysql/, 'mysql2') %>
  url: <%= ENV.fetch("DATABASE_URL") %>
  adapter: postgresql
  encoding: unicode
  database: video-app-share2-db
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POST_HOST") %>
